# Generated by Django 5.2.8 on 2025-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('task_level', models.CharField(choices=[('1', 'Muhim'), ('2', 'Kerak'), ('3', 'Keraksiz'), ('4', 'Sal muhim')], default='1')),
            ],
        ),
    ]
